### ISSUE TITLE
[Security] Workflow release.yml is using vulnerable action metcalfc/changelog-generator

### ISSUE THREAD

**Issue by fockboi-lgtm** [EdwarDDay/serialization.kprefs#172]
The workflow release.yml is referencing action metcalfc/changelog-generator using references v1.0.0. However this reference is missing the commit [14b159ac83976a0eb274f0a9a6c278c3f1b08e87](https://github.com/metcalfc/changelog-generator/commits/14b159ac83976a0eb274f0a9a6c278c3f1b08e87) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by EdwarDDay** [comment]
The workflow [release.yml](https://github.com/EdwarDDay/serialization.kprefs/blob/d7bf4cfd2d0b2f46d0dabe07479674031496b4cb/.github/workflows/release.yml#L32) uses `v3.0.0` of `metcalfc/changelog-generator`. So it uses the fix already.
